<?php

/**
 * @file
 * Contains filial.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\node\NodeInterface;

/**
 * Implements node_view_permissions_node_access().
 */
function filial_node_access(NodeInterface $node, $op, $account) {
  $type = $node->bundle();
  if (FALSE) {
    switch ($op) {
      case 'create':
      case 'create':
      case 'update':
      case 'delete':
        return AccessResult::neutral();

      default:
        return AccessResult::forbidden();
    }
  }
}

/**
 * Implements hook_node_access_records().
 */
function filial_node_access_records(NodeInterface $node) {
  $grants = [];
  if ($node->isPublished() && $node->getType() == 'otziv') {
    $grant = [
      'realm' => 'filial',
      'gid' => 1,
      'grant_view' => 1,
      'grant_update' => 1,
      'grant_delete' => 0,
      'priority' => 0,
    ];
    $grants[] = $grant;
    dsm('filial_node_access_records');
  }

  return $grants;
}

/**
 * Implements hook_node_grants().
 */
function filial_node_grants($account, $op) {
  $grants = [];
  dsm($op);
  if ($op == 'view') {
    $grants['filial'][] = 1;
  }

  return $grants;
}
