<?php

/**
 * @file
 * Contains filial.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function filial_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the filial module.
    case 'help.page.filial':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Filial access content') . '</p>';
      return $output;

    default:
  }
}
